apiVersion: apps/v1
kind: Deployment
metadata:
  name: ekart-deployment
  labels:
    app: flipkart
spec:
  replicas: 3
  selector:
    matchLabels:
      app: flipkart
  template:
    metadata:
      labels:
        app: flipkart
    spec:
      containers:
      - name: flipkart
        image: manish27092007/ekart:latest
        ports:
        - containerPort: 80



apiVersion: v1
kind: Service
metadata:
  name: ekart-deployment
spec:
  selector:
    app: flipkart
  ports:
    - protocol: TCP
      port: 8080
      targetPort: 8080
  type: LoadBalancer
